### ISSUE TITLE
Update build-rosinstall.py to support new time machine

### ISSUE THREAD

**Issue by ChrisTimperley** [robust-rosin/robust#172]

**Comment by gavanderhoorn** [comment]
Sorry, haven't finished it yet .. :(

**Comment by ChrisTimperley** [comment]
> Sorry, haven't finished it yet .. :(

Ah, no worries. Do you expect the interface to be any different to the one used by https://github.com/rosin-project/rosinstall_generator_time_machine/pull/8?

**Comment by gavanderhoorn** [comment]
No.

Or at least not significantly.

If/when the Python version gets here the ros distro arg might need a `--rosdistro=` prepended and the timestamp a `--timestamp`, but that's about it I think.

**Comment by ChrisTimperley** [comment]
> No.
> 
> Or at least not significantly.
> 
> If/when the Python version gets here the ros distro arg might need a `--rosdistro=` prepended and the timestamp a `--timestamp`, but that's about it I think.

Great. Do you mind if I go ahead and update `build-bugzoo.py` to support https://github.com/rosin-project/rosinstall_generator_time_machine/pull/8?

**Comment by gavanderhoorn** [comment]
No, go ahead.

As long as it's clear that people need the PR. And not the current `master`.

Perhaps you could make `build-bugzoo.py` check for presence of the Docker image the new version uses?

**Comment by gavanderhoorn** [comment]
Time machine was upgraded, so `master` branch of that repository now contains the new version.

Docker image is now also v`03`.
