### ISSUE TITLE
Potential problem: cannot fork the same repository twice

### ISSUE THREAD

**Issue by gavanderhoorn** [robust-rosin/robust#18]
At least not with the same account.

I forked `ros_comm` initially for bug `ca23e58` and I can't fork it again now it seems.

I'll try to find a work-around, but we might need to merge all `fixed`+`buggy` branches into a single fork of each repository after all.

**Comment by gavanderhoorn** [comment]
Ok, this appears to not be possible (as expected).

Using a throw-away gh account could allow us to work around this limitation. Not sure though. I'll try that next.

Another option -- if we don't necessarily need to maintain the pedigree/relationship with the original repository -- is to mirror/copy the repository with the put(s) to a mirror/copy on the `robust-rosin` organisation. The same content would be there, it would just not be apparent we forked it (so 'upstream' would be lost).

We could however of course just document that.

**Comment by gavanderhoorn** [comment]
See [robust-rosin/b166c939_kobuki_core](https://github.com/robust-rosin/b166c939_kobuki_core) for an example of such a mirror.

@ChrisTimperley @wasowski: opinions? Do we care about not maintaining the parent-child relationship (as shown on github at least)?

**Comment by ipa-jfh** [comment]
I also do not see another possibility and support this approach.

More of a design change would be to fork the repo once (roboust_<repo>), and then make two branches (<hash>_fixed/buggy) for every bug. But probably we would run into other problems?

**Comment by gavanderhoorn** [comment]
Your second suggestion was something I considered, but that will lead to `2 * <nr_of_bugs>` branches. @wasowski has been busy, and for TF2 (ie: `geometry2`), that would be something like 200-300 branches.

Technically possible, but perhaps not very nice to have to work with.

**Comment by gavanderhoorn** [comment]
I think we'll have to mirror repositories instead of forking, as I've not been able to find a way around the one-fork-per-account/org limit.

The process I followed for `b166c93_kobuki_core` was essentially [Duplicating a repository](https://help.github.com/articles/duplicating-a-repository). This could of course be automated.

**Comment by gavanderhoorn** [comment]
We decided to go with single-forks multiple-branches (:-1:  :smile: ), so closing this.
