### ISSUE TITLE
Migrate to single-fork-many-branch

### ISSUE THREAD

**Issue by gavanderhoorn** [robust-rosin/robust#30]
We'll need to

 - [x] rename the current forks (as they now have a bug id as part of their name)
 - [x] add `REPO_FIX_COMMIT` and `REPO_BUG_COMMIT` to `Dockerfile`
 - [x] update `switch` to use the provided commits.
 - [x] update the various bugzoo yaml files to point to branches/tags

@ChrisTimperley: there's also things for the `Dockerfile` of course, so please feel free to add those to the list (just edit my post).

**Comment by gavanderhoorn** [comment]
I'll also delete [b166c93_kobuki_core](https://github.com/robust-rosin/b166c93_kobuki_core) and need to update #19 to use `eed104d_kobuki_core` instead.

**Comment by wasowski** [comment]
I am still confused so perhaps a silly question. Why delete `b166c93*` repo and use `eed104*` repo? Shouldn't the `eed104d_kobuki_core` be also renamed to `kobuki core` and the bugzoo files should use that name?

**Comment by gavanderhoorn** [comment]
> Why delete `b166c93*` repo

because it is a duplicate of `eed104d_kobuki_core`, which I made using the process described in #18, and since we decided we would not mirror but instead would use single clones with multiple branches. 

`b166c93*` is thus not needed any longer.

> Shouldn't the `eed104d_kobuki_core` be also renamed to `kobuki core` and the bugzoo files should use that name?

Yes, that is what "rename the current forks" is intended to capture.

**Comment by wasowski** [comment]
ah ok.

**Comment by ChrisTimperley** [comment]
@wasowski @gavanderhoorn is there any chance that you could rename the forked repos, or alternatively, could you give me permission to make changes to the forked repos?

**Comment by gavanderhoorn** [comment]
@ChrisTimperley wrote:
> you could rename the forked repos

done.
