### ISSUE TITLE
YAML schema checker: yamale

### ISSUE THREAD

**Issue by gavanderhoorn** [robust-rosin/robust#355]
Would [yamale](https://github.com/23andMe/Yamale) perhaps be an option to use, instead of the current yaml->json route?

**Comment by gavanderhoorn** [comment]
@wasowski @ipa-hsd ?

**Comment by ipa-hsd** [comment]
Will try this out. Thanks @gavanderhoorn

**Comment by gavanderhoorn** [comment]
Ping?

Would probably require different/migrated schema, but seems more efficient as it avoids the conversion.

**Comment by ipa-hsd** [comment]
It looks like the effort out-weighs the benefits (conversion is just another command in the script or it has other "problems"?). For now I would focus on cleaning up the bug files.

**Comment by gavanderhoorn** [comment]
IIUC, yamale will also give you line nrs or direct references to where schema violations are located.

Wasn't that one of the problems you had with the current approach?

I also expect yamale to be much faster than the current approach.

**Comment by ipa-hsd** [comment]
> yamale will also give you line nrs or direct references to where schema violations are located.

My main problem is that it exits after the 1st error it encounters, so I don't get an overview of errors. But I could make a small test for only a section of the bug file to see if I can automate the changes I am making.

**Comment by gavanderhoorn** [comment]
Don't just do it for me of course.

I just wanted to let 'us' know about a possible alternative tool.

**Comment by ipa-hsd** [comment]
Noted :+1:

**Comment by gavanderhoorn** [comment]
I believe yamale is now being used.

so closing
