### ISSUE TITLE
Fix "bug.phase" property in bug reports

### ISSUE THREAD

**Issue by ChrisTimperley** [robust-rosin/robust#361]
In RQ2.1 for the paper, we report the phase in which the associated failure occurs for each bug. That information is currently captured by the `bug.phase` property in the bug reports. Currently, we have a number of different (and redundant) values for this property, shown below.

```
$ grep -h "phase: " -r . | cut -d':' -f2 | sort | uniq
 build-time
 compile-time
 deployment-time
 null
 programming-time
 run-time
 runtime
 runtime-initialization
 runtime-operation
```

I propose that we update the set of acceptable values for the `bug.phase` property to the following:
* `"build"`
* `"deployment"` (e.g., launch failures)
* `"runtime"`
* `"none"` and `"unknown"`

There's some debate to be had about the last value, which we should probably discuss during the meeting today. The idea of having an explicit `"none"` rather than relying on an implicit `null` is to make clear the distinction between the case where we know the associated phase and the case where that information is missing.

**Comment by wasowski** [comment]
So my counter proposal (Also for other properties):

- "build"
- "deployment" (e.g., launch failures)
-  "runtime"
- "does not apply"
- "unknown"

The last two case make the reasons for lack of an actual value clear. @gavanderhoorn

**Comment by gavanderhoorn** [comment]
We decided to rename `deployment` to better reflect the configuration or startup phase.
