### ISSUE TITLE
Ambiguous fix reporting in motoman/91072e8

### ISSUE THREAD

**Issue by ChrisTimperley** [robust-rosin/robust#373]
This is a bit of a strange bug. The pull request that's referenced in the `fix` field is the issue, and the fix commit isn't referenced in the description.

**Comment by gavanderhoorn** [comment]
Fixed this.

The correct PR is https://github.com/ros-industrial/motoman/pull/14, of which ros-industrial/motoman@91072e8c8e680cb700f10d91b1ba01ba5875ff00 is part.
