### ISSUE TITLE
new directory for not-a-bug?

### ISSUE THREAD

**Issue by ipa-hsd** [robust-rosin/robust#404]
`kobuki/b5f0943/b5f0943.bug`: https://github.com/yujinrobot/kobuki/issues/166
`motoman/4089660/4089660.bug`: https://github.com/ros-industrial/motoman/issues/138
`kobuki/496aac8/496aac8.bug`: https://github.com/yujinrobot/kobuki_desktop/issues/18
`geometry2/a2f8eea/a2f8eea.bug`: https://github.com/ros/geometry2/issues/46
`mavros/7c6514d/7c6514d.bug`: https://github.com/mavlink/mavros/pull/296 (not reported)

**Comment by ipa-hsd** [comment]
not quite sure if [geometry2/a2f8eea/a2f8eea.bug](https://github.com/ros/geometry2/issues/46) is really `not-a-bug`

**Comment by gavanderhoorn** [comment]
Does #408 change something here?

**Comment by ipa-hsd** [comment]
No these are different bugs which were marked as `not-a-bug` in the excel sheet, for example the nodelets issue.

**Comment by ipa-hsd** [comment]
Added a `NOT_A_BUG` file instead to the bug folder in https://github.com/robust-rosin/robust/commit/f5d14bd19f4c742855e92de1fc450011920ac99e
