### ISSUE TITLE
System failure code for geometry2/f2568f5

### ISSUE THREAD

**Issue by git-afsantos** [robust-rosin/robust#406]
https://github.com/robust-rosin/robust/blob/master/geometry2/f2568f5/f2568f5.bug

This is categorized as `LOSS-OF-CONTROL`, and I've seen it listed also as a `LOSS-OF-FUNCTIONALITY` example.
From what I understand, any node that uses `tf2_sensor_msgs` at runtime will crash, due to a missing runtime dependency.

How can we be certain that it results in loss of control? Is it due to the specific functions provided by that package?

All it does (in recent versions, at least) is transform point cloud messages.
Since `geometry2` is not a system per se, I think that loss of functionality, if anything, is the most likely end result of this software failure.

**Comment by ChrisTimperley** [comment]
Nice catch. I agree with your assessment that `LOSS-OF-FUNCTIONALITY` seems appropriate, whereas `LOSS-OF-CONTROL` seems unlikely.
