### ISSUE TITLE
Single bugzoo yaml per 'program', or multiple?

### ISSUE THREAD

**Issue by gavanderhoorn** [robust-rosin/robust#44]
Right now we have a single `.bugzoo.yml` per repository / program.

I'm wondering if it would be ok to have one per bug.

If that is ok (for BugZoo as well as us humans), then I think I can automate things a little more.

Opinions?

**Comment by ChrisTimperley** [comment]
BugZoo is fine with any approach: it just scans for all `.bugzoo.yml` files in the repository.

I'm in favour of one per bug.

**Comment by gavanderhoorn** [comment]
I've started with this in #49 and #50.

**Comment by gavanderhoorn** [comment]
@ChrisTimperley: what is the exact pattern that BugZoo scans for?

Would having just a `bugzoo.yml` also work?

**Comment by ChrisTimperley** [comment]
@gavanderhoorn it scans for all files ending in `.bugzoo.yml`.

**Comment by gavanderhoorn** [comment]
I've just ended up with a single `manifest.bugzoo.yml` in the bug dir.
